echo  '              eUIloveUI           IloveUIlo'
echo  '          loveUIloveUIloveU   veUIloveUIloveUIl'
echo  '        IloveUIloveUIloveUIloveUIloveUIloveUIlove'
echo  '       IloveUIloveUIloveUIloveUIloveUIloveUIloveUI'
echo  '      IloveUIloveUIloveUIloveUIloveUIloveUIloveUIlo'
echo  '      loveUIloveUIloveUIloveUIloveUIloveUIloveUIlov'
echo  '      oveUIloveUIloveUIloveUIloveUIloveUIloveUIlove'
echo  '      veUIloveUIloveUIloveUIloveUIloveUIloveUIloveU'
echo  '      eUIloveUIloveUIloveUIloveUIloveUIloveUIloveUI'
echo  '      UIloveUIloveUIloveUIloveUIloveUIloveUIloveUIl'
echo  '       loveUIloveUIloveUIloveUIloveUIloveUIloveUIl'
echo  '        veUIloveUIloveUIloveUIloveUIloveUIloveUIl'
echo  '        eUIloveUIloveUIloveUIloveUIloveUIloveUIlo'
echo  '          loveUIloveUIloveUIloveUIloveUIloveUIl'
echo  '           veUIloveUIloveUIloveUIloveUIloveUIl'
echo  '            UIloveUIloveUIloveUIloveUIloveUIl'
echo  '              oveUIloveUIloveUIloveUIloveUI'
echo  '                UIloveUIloveUIloveUIloveU'
echo  '                  oveUIloveUIloveUIlove'
echo  '                     IloveUIloveUIlo'
echo  '                        eUIloveUI'
echo  '                           ove'
echo  '                            e'